export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESSFULLY_ADDED_PRODUCT = 'SUCCESSFULLY_ADDED_PRODUCT';
export const ERROR_ADDING_PRODUCT = 'ERROR_ADDING_PRODUCT';

export const PRODUCTS_DOWNLOAD = 'PRODUCTS_DOWNLOAD';
export const SUCCESSFUL_PRODUCTS_DOWNLOAD = 'SUCCESSFUL_PRODUCTS_DOWNLOAD';
export const WRONG_PRODUCTS_DOWNLOAD = 'WRONG_PRODUCTS_DOWNLOAD';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SUCCESSFUL_PRODUCT_DELETE = 'SUCCESSFUL_PRODUCT_DELETE';
export const WRONG_PRODUCT_DELETE = 'WRONG_PRODUCT_DELETE';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SUCCESSFUL_PRODUCT_EDIT = 'SUCCESSFUL_PRODUCT_EDIT';
export const WRONG_PRODUCT_EDIT = 'WRONG_PRODUCT_EDIT';

export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const START_SET_EDIT_PRODUCT = 'START_SET_EDIT_PRODUCT';
export const SET_PRODUCT_EDIT = 'SET_PRODUCT_EDIT';
export const WRONG_SET_PRODUCT_EDIT = 'WRONG_SET_PRODUCT_EDIT';