export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SUCCESSFULLY_ADDED_PRODUCT = 'SUCCESSFULLY_ADDED_PRODUCT';
export const ERROR_ADDING_PRODUCT = 'ERROR_ADDING_PRODUCT';

export const PRODUCTS_DOWNLOAD = 'PRODUCTS_DOWNLOAD';
export const SUCCESSFUL_PRODUCTS_DOWNLOAD = 'SUCCESSFUL_PRODUCTS_DOWNLOAD';
export const WRONG_PRODUCTS_DOWNLOAD = 'WRONG_PRODUCTS_DOWNLOAD';